openapi: 3.0.0
info:
  title: FM Inventory
  description: FM Inventory
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Category
  - name: Discount
  - name: Vendor
  - name: Coshh
  - name: Client Group
  - name: Item
  - name: Order
  - name: File
  - name: Color
  - name: Size
paths:
  /api/category:
    post:
      tags:
        - Category
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Sub Title 2
                detail:
                  type: string
                  example: |-
                    alkdsjwjaldjald
                    adklwjalkjsdkljwakl
                inventory_forecast_id:
                  type: string
                  example: asldj01-=10i10123
                parent_id:
                  type: integer
                  example: '3'
                status:
                  type: integer
                  example: '0'
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Category
      summary: index
      security:
        - bearerAuth: []
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: status
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
          example: TITLE
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
        - name: paginate
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/category/{category_id}:
    post:
      tags:
        - Category
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Title 1 Edited
                detail:
                  type: string
                  example: |-
                    alkdsjwjaldjald
                    adklwjalkjsdkljwakl
                inventory_forecast_id:
                  type: string
                  example: asdws
                parent_id:
                  type: integer
                  example: '2'
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: category_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Category
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: category_id
          in: path
          schema:
            type: integer
          required: true
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/discount:
    post:
      tags:
        - Discount
      summary: store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                campaign_title: Title
                percentage: 50.11
                start_date: '2022-02-02'
                end_date: '2023-01-01'
                created_by: awldkj2lj3109-1231
                approved_by: alkdjw2-192310-13
                status: inprogress
                item_ids:
                  - 1
                  - 2
                  - 4
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Discount
      summary: index
      security:
        - bearerAuth: []
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: status
          in: query
          schema:
            type: string
          description: 'values: [approved, inprogress, pending]'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/discount/{discount_id}:
    post:
      tags:
        - Discount
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                campaign_title: Title edited
                percentage: 55.11
                start_date: '2022-01-01'
                end_date: '2023-01-01'
                created_by: awldkj2lj3109-1231
                approved_by: alkdjw2-192310-14
                status: inprogress
                item_ids:
                  - 5
                  - 7
                  - 8
                _method: PUT
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: discount_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Discount
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: discount_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Discount
      summary: delete
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: discount_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/vendor:
    post:
      tags:
        - Vendor
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bishal Gurung
                phone:
                  type: integer
                  example: '1231'
                email:
                  type: string
                  example: asdw@gmai.com
                contact_persion:
                  type: integer
                  example: '1312'
                status:
                  type: integer
                  example: '0'
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Vendor
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: status
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
        - name: sort_order
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/vendor/{vendor_id}:
    post:
      tags:
        - Vendor
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Bishal Gurung
                phone:
                  type: integer
                  example: '989898'
                email:
                  type: string
                  example: grgbishal360@gmail.com
                contact_persion:
                  type: string
                  example: awalkjddkl
                status:
                  type: integer
                  example: '1'
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: vendor_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Vendor
      summary: find by id
      parameters:
        - name: organization_id
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: vendor_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/coshh:
    post:
      tags:
        - Coshh
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Coshh 2
                description:
                  type: string
                  example: |
                    alsdjlakjd
                    asjdlkwjdaklsjdklsajdwa
                safety_guidelines:
                  type: string
                  example: |-
                    aldjwaidj
                    adlkwajdwlkjdalkd
                image:
                  type: string
                  format: binary
                status:
                  type: string
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Coshh
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: status
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
          example: name
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/coshh/{coshh_id}:
    post:
      tags:
        - Coshh
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Coshh 1 edited
                description:
                  type: string
                  example: |
                    alsdjlakjd
                    asjdlkwjdaklsjdklsajdwa
                safety_guidelines:
                  type: string
                  example: ald
                status:
                  type: integer
                  example: '0'
                image:
                  type: string
                  format: binary
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: coshh_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Coshh
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: coshh_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/client-group:
    post:
      tags:
        - Client Group
      summary: store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Client Group 3
                client_ids:
                  - 1
                  - 2
                  - asd-123
                status: 1
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Client Group
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: status
          in: query
          schema:
            type: integer
          example: '1'
        - name: paginate
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: sort_key
          in: query
          schema:
            type: string
          example: name
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/client-group/{client_group_id}:
    post:
      tags:
        - Client Group
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Client Group Edited
                client_ids:
                  - 1
                  - 4
                  - 5
                status: 1
                _method: PUT
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: client_group_id
          in: path
          schema:
            type: integer
          required: true
          example: '9'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Client Group
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: client_group_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/client-group/{client_id}/client:
    get:
      tags:
        - Client Group
      summary: find client group by client id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: client_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/client-group/client-ids-occupied:
    get:
      tags:
        - Client Group
      summary: get occupied client ids
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/item:
    post:
      tags:
        - Item
      summary: store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Item 1
                price: 123
                description: alsdjlakjd↵asjdlkwjdaklsjdklsajdwa
                used_for: adws
                category_id: 1
                sub_category_id: 3
                coshh_ids:
                  - 1
                  - 3
                status: 1
                variations:
                  - vendor_id: 123ads
                    size: large
                    color: black
                    price: 200
                    quantity: 5
                    sku: sku123
                  - vendor_id: 123ads
                    size: medium
                    color: pink
                    price: 100
                    quantity: 2
                    sku: sku124
                  - vendor_id: 123ads
                    size: xxl
                    color: white
                    price: 400
                    quantity: 8
                    sku: sku125
                risk_assessments:
                  abc: ab
                  b: bcde
      security:
        - bearerAuth: []
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Item
      summary: index
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: status
          in: query
          schema:
            type: string
        - name: paginate
          in: query
          schema:
            type: integer
          example: '1'
        - name: limit
          in: query
          schema:
            type: integer
          example: '100'
        - name: sort_key
          in: query
          schema:
            type: string
          example: id
        - name: sort_order
          in: query
          schema:
            type: string
          example: asc
        - name: coshh_id
          in: query
          schema:
            type: string
        - name: category_id
          in: query
          schema:
            type: string
        - name: sub_category_id
          in: query
          schema:
            type: string
        - name: client_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/item/{item_id}:
    post:
      tags:
        - Item
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Item 1 edited
                price: 123
                description: alsdjlakjd↵asjdlkwjdaklsjdklsajdwa
                used_for: adws
                category_id: 1
                sub_category_id: 3
                coshh_ids:
                  - 1
                  - 3
                status: 1
                variations:
                  - id: 17
                    vendor_id: '123'
                    size: L
                    color: Black
                    price: 200
                    quantity: null
                    sku: sku123
                  - id: 18
                    vendor_id: '123'
                    size: XXL
                    color: White
                    price: 400
                    quantity: 8
                    sku: sku125
                risk_assessments:
                  abc: ab
                  b: bcde
                _method: PUT
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: item_id
          in: path
          schema:
            type: integer
          required: true
          example: '16'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Item
      summary: find by id
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: item_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/item/{client_group_id}/client-group:
    post:
      tags:
        - Item
      summary: add items by client group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                item_variation_ids:
                  - 1
                  - 2
                  - 3
                  - 4
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: client_group_id
          in: path
          schema:
            type: integer
          required: true
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/item/{client_id}/client-id:
    post:
      tags:
        - Item
      summary: add items by client id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                item_variation_ids:
                  - 2
                  - 3
                  - 4
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: 33d5fc59-963d-4bb6-b429-117ee601826d
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: client_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order:
    post:
      tags:
        - Order
      summary: create new order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: 1a
                ordered_by: 2b
                ordered_date: 2022/12/13
                delivery_date: 2022/12/25
                delivery_time: 10:20 am
                status: approved
                approved_by: ''
                details:
                  - item_id: 1
                    size: medium
                    color: pink
                    quantity: 2
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Order
      summary: get all orders
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: client_id
          in: query
          schema:
            type: string
          example: 1a
        - name: sort_key
          in: query
          schema:
            type: string
          description: 'default: "ordered_date"'
        - name: sort_order
          in: query
          schema:
            type: string
          description: 'values: ["ASC", "DESC"], default: "DESC"'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order/{order_id}:
    post:
      tags:
        - Order
      summary: update order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                delivery_date: 2023/12/25
                delivery_time: 1:36 am
                approved_by: asdw
                details:
                  - item_id: 1
                    size: large
                    color: black
                    quantity: 3
                _method: PUT
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: order_id
          in: path
          schema:
            type: integer
          required: true
          example: '42'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Order
      summary: get single order
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: order_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Order
      summary: delete order
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: order_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/order/{order_id}/update-status:
    post:
      tags:
        - Order
      summary: update order status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                status: pending
                approved_by: user-126
                _method: put
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: order_id
          in: path
          schema:
            type: integer
          required: true
          example: '18'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/file:
    post:
      tags:
        - File
      summary: upload file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/color:
    get:
      tags:
        - Color
      summary: get all colors
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Color
      summary: create color
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Blue
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/color/{color_id}:
    post:
      tags:
        - Color
      summary: update color
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Yellow
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: color_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Color
      summary: delete color
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: color_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Color
      summary: delete color Copy
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: color_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/size:
    get:
      tags:
        - Size
      summary: get all sizes
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Size
      summary: create size
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: large
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/size/{size_id}:
    post:
      tags:
        - Size
      summary: update size
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: XXL
                _method:
                  type: string
                  example: PUT
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: size_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Size
      summary: delete size
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: size_id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Size
      summary: get single size
      parameters:
        - name: organizationId
          in: header
          schema:
            type: string
          example: '{{organization_id}}'
        - name: size_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
